Tudmotu/gnome-shell-extension-clipboard-indicator

extension.js
This is really really subjective matter but ... how about using the "paste" icon instead of "cut" on the clipboard indicator ? It's a little closer to the extension job, which is all about what we want to paste, and the paste symbolic icon has a nice clipboard look too. Or maybe the "cut" has some special meaning for you ?
We may also go further and add a preference where one can choose between cut/copy/paste icons. 
Edit :
In case you wonder what is the 'paste' icon, here it is :
=> Suggestion : Change icon to paste

extension.js
If you keep a number of commit too large, the menu grows too big and you can see with a click which is the last you have in there. By reverting the order and placing latest elements on top, you fix this situation.
=> menu: put latest element on top

extension.js
I couldn't set focus to a menu item, but if you push UP arrow it will focus on the first item and ENTER works now! If somebody knows how to set focus, please help me or create a pull request, it should be just one line around `extension.js:450`! I've already tried:
```js
this.clipItemsRadioGroup[0].focus();
this.clipItemsRadioGroup[0].emit('focus');
this.clipItemsRadioGroup[0].emit('focus:');
this.clipItemsRadioGroup[0].emit('object:state-changed:focused');
this.clipItemsRadioGroup[0].emit('object:state-changed:focused', true);
...
```
Nothing seems to work :(
=> Fixes #9: When indicator menu is open, navigate using arrows and select with ENTER

extension.js
Update the _toggleMenu function to use .menu.toggle() as the existing menu visibility check does not work.
=> Fix 'Toggle the menu' function

extension.js
This fixes the disconnection of the the signal handler when removing old entries which was throwing gsignal instance has no handler with id errors.
=> Fix signal handler disconnect

extension.js
Just add a X icon next to the current clipboard item to delete it.
It works because if you click on it, it sets the current clipboard to '' too, so item doesn't come back. Clipboard.get_text() doesn't add entry when clipboard = '' to avoid useless '' item in clipboard indicator.
=> delete current clipboard

extension.js
Correction of this error (at boot time) : 
gnome-shell[6944]: JS ERROR: TypeError: string is null
ClipboardIndicator<._truncate@/home/$$$/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:211:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
ClipboardIndicator<._updateButtonText@/home/$$$/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:98:35
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
ClipboardIndicator<._onPrivateModeSwitch/<@/home/$$$/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:460:29
=> dont truncate if no content

metadata.json
_This PR only update the manifest, not tested if needs specific adaptations_
GNOME Shell 3.36 was released but it wasn't possible to install this application on it
=> Allow installation for 3.36

extension.js
GS 3.36 introduced a portal-like API for actions like opening settings.
That was done in order to make it possible to ship the new extensions
app in a sandboxed manner, e.g. via flatpak.
While talking to the API directly is a bit cumbersome, luckily there
is a convenience function we can make use of (from GS 3.36.2 on).
Closes https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/202
This depends on https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163 to land first -> ~WIP~ -> MR landed now
=> Use new convenience function to open settings

extension.js, metadata.json
- remove deprecated this.actor usage
- remove deprecated x_fill usage
- set more properties in constructors
- use `x_expand`/`y_expand`
- remove pre-3.36 support
Closes #230, closes #228, closes #192
=> Gnome 3.38 support

extension.js, metadata.json, prefs.js, schemas/org.gnome.shell.extensions.clipboard-indicator.gschema.xml
**extension.js**
Removed the deprecated actor for ClipboardIndicator.
**prefs.js**
- _Gtk.accelerator_parse()_ now returns first element as ok.
- _show_all()_ no longer works and needed on GTK4.
- Instead of _HBox_ use Gtk.Box.
- _margin_ no longer supported in GTK4 and replaced with more detailed margin properties.
**metadata.json**
Removed "3.38" and added "40.0" to the shell version.
=> Gnome Shell 40 Port

confirmDialog.js
Repeating "clear-history" keyboard shortcut (by default, `<Ctrl>F10`)
results in opening multiple confirm dialogues.
=> Prevent from opening multiple dialogs

extension.js
Hey @Tudmotu, thanks for the amazing tool, I do not know how I can work without it! 
This fixes #210, and updates the preview in the following cases which were not there earlier:
- When the extension is restarted
- Previous or next content selected through keyboard bindings
- Another selection is made through the dropdown menu
Tested locally. Let me know if you need anything else.
=> update topbar preview on selection from menu

extension.js, prefs.js, schemas/org.gnome.shell.extensions.clipboard-indicator.gschema.xml
There is currently no option for disabling the confirmation dialog when clearing the history.
This adds a toggle in the settings for enabling/disabling the confirmation dialog.
=> Add toggle for confirmation on clear history

extension.js, metadata.json
Register ClipboardIndicator using GObject.registerClass(). Fix https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/342. It seems that ClipboardIndicator cannot be defined with Lang.Class since gnome shell 42. But I'm not sure why.
=> GNOME 42 support

extension.js
1. Pressing the delete button when on a highlighted entry removes the entry
2. After the entry is removed the focus shifts to the next item and if empty then to the private
Tested it on GNOME OS Nightly ( via GNOME Boxes )
Fixes #375
=> feat: pressing delete removes higlighted entry (#1) 

extension.js
Changes 
1. Finding the next available menu item  ( include extra cases )
2. The focus of the next item event comes before the actual delete or favorite key event
Fixes #375
=> bugfix: select next item after delete key event, favourite key event

extension.js
Simple port of [commit from the Clipboard History](https://github.com/SUPERCILEX/gnome-clipboard-history/commit/7e22dc026c73ed4a27b447529c4fae5cb6ec74c2) extension.
=> Disable notifications for "Do Not Disturb" and "Private" modes

extension.js
Fixes #404.
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length#strings_with_length_not_equal_to_the_number_of_characters
=> Truncate text based on graphemes instead of code units

registry.js
The idea of the fix comes from @gentoo-root, @AmeyaVS and @alephnull
comments in the original issue:
Changing "UTF8_STRING" to "text/plain;charset=utf-8" in registry.txt
seems to be fixing the problem after reloading the extension.
So let's use this.isText() instead of mimetype.startsWith('text/')) in
fromJSON text checking.
Without this patch "Text will be here" appears in the tray and extension
is unresponsive.
Fixes: #459
=> Fix UTF8_STRING in registry.txt renders extension unresponsive on Gnome 46 (Wayland)

stylesheet.css
This fixes the extra spacing/margins added to menu items in all gnome panel menus bug mentioned in issue #483. The CSS was too general, so it targeted all gnome panel menu items.
It also removed unneeded left space added to clipboard history menu items since only a right margin was needed.
**Before:**
**After:**
=> Fix Extra Spacing In All Gnome Shell Menus

extension.js
This is a temporary fix for #513 until https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/8233 is fixed
It probably won't break old applications, but I can't find anything to test this with
=> Fix issue #513 (2nd+ copy having wrong mimetypes)

extension.js
This fixes #490.
The issue was that the buttonImgPreview wasnt being hidden even when having only show icon in settings enabled. This way altough it didnt show any images, as some other code handled that, it still took space, moving the icon.
_I think the preview is still not complety in the center, but thats due to the fact, that the size of the icon and the size of the tray box dont match, e.g. box is 5 px and the preview is 2 px, so there is no way to completely center the preview._
=> Fix icon being offcenter
