- extension.js
> Using Notify for notifications

- README.rst
- extension.js
It's not perfect but it's simple and it works :)
> Implementation of a basic search feature

- utils.js
> Correct usage of toString on Uint8Array

- prefs.js
Fixes #102
Follow up to ac96d1a591bd423ed986e3719efc39e58de9e3ed
> Allow setting history size up to 200 in settings.

- extension.js
> add cancel action to copied to clipboard notifications

- locale/cs/LC_MESSAGES/clipboard-indicator.po
What about .mo file - will it be regenerated, or is there need to replace it manualy?
> Update Czech localization

- locale/it/LC_MESSAGES/clipboard-indicator.po
Translation completed. I don't know how to manage the last translator and language team thing (lines 12 and 13) so feel free to modify. However I put my email address.
> Update Italian clipboard-indicator.po

- bundle.sh
- confirmDialog.js
- extension.js
Add confirmation dialog to the extension.
Addressing #182
> Adding confirmation dialog for clear all the items

- confirmDialog.js
- extension.js
> Fix `meta is null` on "Clear history" button pressed

- locale/cs/LC_MESSAGES/clipboard-indicator.po
hi, fast and clean update of just .po file
> update czech translation

- metadata.json
I have tested it on my system and it works.
> Bump supported shell to 44

- metadata.json
just adding gnome 45 in metadata.json, tested and working.
> Update metadata.json to gnome 45

- locale/es/LC_MESSAGES/clipboard-indicator.po
I saw you added more texts to translate, so I added the translations.
Thank you for such a great Gnome extension.
> Complete and correct Spanish translations

- locale/it/LC_MESSAGES/clipboard-indicator.po
> Update Italian language

- extension.js
Catch unlikely errors in a GSettings callback.
closes #448
> Fix unhandled Promise exception

- registry.js
The clipboard content type may be a filename represented by a variety of mime-types, so double-check it is supported type before loading the contents.
closes #447
closes #453
> registry: don't trust the clipboard content type

- registry.js
> fix: Unhandled promise rejection on registry

- stylesheet.css
> Fix: Scroll Bar was Inaccessible To Mouse

- locale/fr_FR/LC_MESSAGES/clipboard-indicator.po
> Update (french) clipboard-indicator.po

- locale/zh_CN/LC_MESSAGES/clipboard-indicator.po
Correct mistakes and update translation in zh-cn
> Corrected a mistake, updated new translations and line numbers

- metadata.json
Untested since I'm on 47. Hopefully solves #509
> Update For GNOME 48 Support

- prefs.js
The most important changes is the addition of a popover for selecting installed applications and a search functionality within the popover. The selected applications id, which will also be the wmclass of the apps window, will then be filled into the inout field. This is in response to [this](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/407#issuecomment-2761613436) comment
---
> Add button when adding excluded apps for searching all applications
